2017-11-12 23:01:35,523 ERROR: HTTP_STATUS_CODE_500: {'message': 'Internal Server Error.', 'code': 500} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/minion.py", line 64, in list_minions
    sort_key = args['sort']['key']
KeyError: 'key'
2017-11-12 23:07:42,413 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-12 23:07:42,413 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-12 23:07:58,711 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-12 23:07:58,712 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-12 23:37:24,619 ERROR: HTTP_STATUS_CODE_422: {'message': 'Validation error, re-check your data.', 'code': 422} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/account.py", line 129, in add_account
    json_data = parser.parse(params)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 363, in parse
    self._on_validation_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 310, in _on_validation_error
    self.handle_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 105, in handle_error
    abort(status_code, messages=error.messages, exc=error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 40, in abort
    raise err
UnprocessableEntity: 422 Unprocessable Entity: {'message': 'Validation error, re-check your data.', 'code': 422}
2017-11-12 23:39:52,550 ERROR: HTTP_STATUS_CODE_422: {'message': 'Validation error, re-check your data.', 'code': 422} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/account.py", line 129, in add_account
    json_data = parser.parse(params)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 363, in parse
    self._on_validation_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 310, in _on_validation_error
    self.handle_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 105, in handle_error
    abort(status_code, messages=error.messages, exc=error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 40, in abort
    raise err
UnprocessableEntity: 422 Unprocessable Entity: {'message': 'Validation error, re-check your data.', 'code': 422}
2017-11-12 23:40:00,284 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-12 23:40:00,285 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-12 23:40:04,124 ERROR: HTTP_STATUS_CODE_422: {'message': 'Validation error, re-check your data.', 'code': 422} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/account.py", line 129, in add_account
    json_data = parser.parse(params)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 363, in parse
    self._on_validation_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 310, in _on_validation_error
    self.handle_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 105, in handle_error
    abort(status_code, messages=error.messages, exc=error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 40, in abort
    raise err
UnprocessableEntity: 422 Unprocessable Entity: {'message': 'Validation error, re-check your data.', 'code': 422}
2017-11-12 23:44:17,910 ERROR: HTTP_STATUS_CODE_500: {'message': 'Internal Server Error.', 'code': 500} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/account.py", line 130, in add_account
    account_number = json_data['account_number'].strip()
AttributeError: 'int' object has no attribute 'strip'
2017-11-12 23:44:27,457 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-12 23:44:27,458 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-12 23:44:32,016 ERROR: HTTP_STATUS_CODE_500: {'message': 'Internal Server Error.', 'code': 500} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/account.py", line 130, in add_account
    account_number = json_data['account_number'].strip()
AttributeError: 'int' object has no attribute 'strip'
2017-11-12 23:45:03,819 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-12 23:45:03,819 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-12 23:45:09,061 ERROR: HTTP_STATUS_CODE_500: {'message': 'Internal Server Error.', 'code': 500} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/account.py", line 137, in add_account
    'balance': json_data['balance', ''],
KeyError: ('balance', '')
2017-11-12 23:46:44,223 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-12 23:46:44,223 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 00:12:10,037 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 00:12:10,037 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 00:37:39,007 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 00:37:39,007 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 00:38:13,777 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 00:38:13,777 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 00:43:09,852 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 00:43:09,853 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 01:04:08,541 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 01:04:08,542 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 01:04:45,016 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 01:04:45,016 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 01:04:47,975 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 01:04:47,976 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 01:06:17,476 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 01:06:17,477 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 01:09:26,693 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 01:09:26,702 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 04:02:03,852 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 04:02:03,852 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 05:21:45,890 ERROR: HTTP_STATUS_CODE_405: {'message': 'Method Not Allowed.', 'code': 405} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1590, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1573, in raise_routing_exception
    raise request.routing_exception
MethodNotAllowed: 405 Method Not Allowed: {'message': 'Method Not Allowed.', 'code': 405}
2017-11-13 07:55:58,189 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 07:55:58,190 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 22:37:49,136 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 22:37:49,146 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 23:12:04,752 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 23:12:04,753 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 23:44:03,022 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 23:44:03,022 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-13 23:44:44,919 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-13 23:44:44,919 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:10:46,079 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:10:46,080 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:21:32,734 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:21:32,738 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:21:54,516 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:21:54,517 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:22:16,989 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:22:16,989 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:23:39,023 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:23:39,023 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:23:55,989 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:23:55,990 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:26:07,300 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:26:07,300 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:32:31,392 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:32:31,392 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:35:35,896 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:35:35,900 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:37:39,422 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:37:39,422 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 01:51:08,187 ERROR: HTTP_STATUS_CODE_422: {'message': 'Validation error, re-check your data.', 'code': 422} [in /home/quynt13/Desktop/ACBank/agentstats-api/app/exceptions.py:191]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_oauth2/resources/__init__.py", line 37, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_permissions/permissions/__init__.py", line 57, in decorated
    return f(*args, **kwargs)
  File "/home/quynt13/Desktop/ACBank/agentstats-api/app/api/agent.py", line 42, in list_agents
    args = parser.parse(params)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 363, in parse
    self._on_validation_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 310, in _on_validation_error
    self.handle_error(error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 105, in handle_error
    abort(status_code, messages=error.messages, exc=error)
  File "/usr/local/lib/python2.7/dist-packages/webargs/flaskparser.py", line 40, in abort
    raise err
UnprocessableEntity: 422 Unprocessable Entity: {'message': 'Validation error, re-check your data.', 'code': 422}
2017-11-14 01:53:32,508 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 01:53:32,508 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
2017-11-14 06:49:31,827 INFO: Config filename: app/config.py [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:109]
2017-11-14 06:49:31,827 INFO: App log folder: /home/quynt13/Desktop/ACBank/agentstats-api/logs [in /home/quynt13/Desktop/ACBank/agentstats-api/app/app.py:110]
